<?php
require_once(__DIR__ . '/../config/rutes.php');
require_once(ROOT_PATH . 'auth/session_manager.php');

?>
<!DOCTYPE html>
<html lang="es" >
<head>
  <meta charset="UTF-8">
  <link rel="icon" type="image/svg+xml" href="../assets/img/general/favicon.ico?v=2" />
  <title>Animacion svg</title>
<style>
/*****************************************
 * Basic styling, scroll down for the
 * SVG stroke animation code
 *****************************************/

body * {
  box-sizing: border-box;
}

html, body {
  height: 100%;
  margin: 0;
  padding: 0;
  font-family: sans-serif;
  color: #fff;
  overflow-x:hidden;
  overflow-y:hidden;
}

.wrapper {
  background: #120433;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  padding: 1em;
}

.title {
  margin: 0 0 1em;
  padding: 0;
  font: normal 1.2em sans-serif;
  text-transform: uppercase;
  letter-spacing: 2px;
}

.controls {
  margin: 1rem 0 0;
}

button {
  font: bold .875em sans-serif;
  background-color: hsl(200,30%,90%);
  color: #454545;
  padding: .4em .6em .3em;
  border: none;
  text-transform: uppercase;
  border-radius: .4em;
  margin: 0 .5em;
  box-shadow: 0px 2px 10px hsla(0,0%,0%,.3);
}

button:hover {
  background-color: #fff;
}

button:active {
  background-color: hsl(200,30%,90%);
  transform: translateY(2px);
  box-shadow: 0px 0px 2px hsla(0,0%,0%,.3);
}
@media screen and (max-width: 991px) {
  .wrapper {
    padding: 9em;
  }
}
  /***************************************************
 * Generated by SVG Artista on 5/3/2024, 1:41:09 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

svg .svg-elem-1 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-1 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-2 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-2 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-3 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-3 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-4 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-4 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-5 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-5 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-6 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-6 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-7 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-7 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-8 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-8 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-9 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-9 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-10 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-10 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-11 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-11 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-12 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-12 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-13 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-13 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-14 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-14 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-15 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-15 {
  fill: rgb(255, 255, 255);
}

svg .svg-elem-16 {
  fill: transparent;
  -webkit-transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
          transition: fill 0.6s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
}

svg.active .svg-elem-16 {
  fill: rgb(255, 255, 255);
}
  
    

</style>
</head>
<body translate="no">
  <div class="wrapper">
  <h2 class="title">CARGANDO...</h2>
<svg id="Capa_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 1080" width="1080" height="1080"><defs><style>.cls-1{fill:#fff;stroke-width:0px;}</style></defs><path class="cls-1 svg-elem-1" d="M437.9,853.67c-234.31-29.54-410.73-158.71-410.73-313.62S203.8,255.77,438.31,226.33h0c-214.41,31.28-373.96,159.78-373.96,313.72s159.89,281.97,373.55,313.62h0Z"></path><path class="cls-1 svg-elem-2" d="M650.44,852.56c210.04-33.45,366.35-160.67,366.35-312.52s-156.96-279.6-367.66-312.73l1.69.21c229.96,31.61,402.01,159.52,402.01,312.52s-172.22,281.01-402.38,312.52h0"></path><path class="cls-1 svg-elem-3" d="M753.21,554.93h171.43s23.09,40.26-7.06,95.59c-30.15,55.33-99.59,45.03-99.59,45.03h-104.55v-79.75h108.37s24.04,4.2,25.57-17.17c1.53-21.37-20.99-19.84-20.99-19.84,0,0-36.82,3.82-73.17-23.85Z"></path><path class="cls-1 svg-elem-4" d="M468.42,375.63l-84.56,81.06h-114.3s-23.33-3.5-21.58,16.33c1.75,19.83,15.16,25.08,52.48,25.66,37.32.58,65.89,36.15,65.89,36.15h-180.19s-32.66-43.74-12.25-98.55c20.41-54.82,89.22-61.23,89.22-61.23l205.27.58Z"></path><polygon class="cls-1 svg-elem-5" points="199.3 537.75 379.78 537.75 388.53 551.16 212.42 551.16 199.3 537.75"></polygon><path class="cls-1 svg-elem-6" d="M206.88,554.08h174.65s23.52,41.01-7.19,97.38c-30.71,56.37-101.47,45.87-101.47,45.87h-106.52v-81.25h110.41s24.49,4.28,26.05-17.49c1.56-21.77-21.38-20.22-21.38-20.22,0,0-37.52,3.89-74.54-24.3Z"></path><path class="cls-1 svg-elem-7" d="M929.49,375.63l-.97,81.06h-114.3s-23.33-3.5-21.58,16.33c1.75,19.83,15.16,25.08,52.48,25.66,37.32.58,65.89,36.15,65.89,36.15h-180.19s-32.66-43.74-12.25-98.55c20.41-54.82,89.22-61.23,89.22-61.23l121.68.58Z"></path><polygon class="cls-1 svg-elem-8" points="743.95 537.75 924.44 537.75 933.18 551.16 757.08 551.16 743.95 537.75"></polygon><path class="cls-1 svg-elem-9" d="M751.54,554.08h174.65s23.52,41.01-7.19,97.38c-30.71,56.37-101.47,45.87-101.47,45.87h-106.52v-81.25h110.41s24.49,4.28,26.05-17.49c1.56-21.77-21.38-20.22-21.38-20.22,0,0-37.52,3.89-74.54-24.3Z"></path><path class="cls-1 svg-elem-10" d="M498.74,375.05l-87.47,87.47-.58,72.31h87.47v-79.31h69.98s34.99-.58,34.99,34.41-31.49,39.07-31.49,39.07l-56.56.58,6.22,5.44h151.81s27.99-31.1,12.83-95.25c-15.16-64.15-96.8-65.31-96.8-65.31l-90.39.58Z"></path><polygon class="cls-1 svg-elem-11" points="410.98 553.78 498.16 553.78 498.16 697.24 410.69 697.24 410.98 553.78"></polygon><polygon class="cls-1 svg-elem-12" points="542.48 553.78 690.6 698.4 690.6 596.65 648.9 554.66 653.86 553.49 542.48 553.78"></polygon><rect class="cls-1 svg-elem-13" x="421.19" y="537.55" width="87.67" height="13.61"></rect><path class="cls-1 svg-elem-14" d="M534.32,537.75h147.53s-5.44,8.94-11.86,13.61h-122.07l-13.61-13.61Z"></path><path class="cls-1 svg-elem-15" d="M1030.43,822.52c-18.66,4.96-35.3-11.67-30.36-30.33,2.17-8.2,8.8-14.83,16.99-17.01,18.66-4.96,35.3,11.66,30.36,30.32-2.17,8.2-8.8,14.83-16.99,17.01ZM1029.19,779.56c-15.21-4.04-28.76,9.52-24.73,24.73,1.77,6.68,7.17,12.08,13.85,13.86,15.21,4.04,28.76-9.52,24.73-24.73-1.77-6.68-7.17-12.08-13.85-13.85Z"></path><path class="cls-1 svg-elem-16" d="M1037.25,810.76h-4.89l-4.57-6.66c-.53-.77-1.01-1.41-1.45-1.92-.43-.51-.88-.92-1.33-1.22-.45-.31-.94-.52-1.47-.64s-1.14-.18-1.85-.18h-3.47v10.63h-3.99v-24.37h11.57c1.43,0,2.72.11,3.86.34,1.14.23,2.12.6,2.92,1.13.8.52,1.41,1.21,1.85,2.06.43.85.64,1.9.64,3.16,0,1.86-.62,3.36-1.85,4.51-1.24,1.15-3.06,1.88-5.48,2.2v.09c1.76.7,3.4,2.15,4.93,4.35l4.57,6.54ZM1018.24,797.06h6.75c1.96,0,3.45-.31,4.48-.92,1.03-.62,1.54-1.64,1.54-3.06,0-1.13-.44-1.99-1.32-2.58-.88-.59-2.3-.89-4.25-.89h-7.2v7.46Z"></path></svg>


  <div class="controls" style="visibility:hidden;">
    <button class="btn-draw">DIBUJAR</button>  
    <button class="btn-erase">BORRAR</button> 
  </div>
</div>
  
<script>
    var wrapper = document.querySelector('.wrapper svg');
    var btnDraw = document.querySelector('.btn-draw');
    var btnErase = document.querySelector('.btn-erase');

    // We are only adding and removing the 'active' class,
    // the entire animation is defined in the CSS code
    function draw() {
    wrapper.classList.add('active');
    }

    function erase() {
    wrapper.classList.remove('active');
    }

    // Add handlers to our buttons
    btnDraw.addEventListener('click', draw, false);
    btnErase.addEventListener('click', erase, false);

    // Play draw animation once
    setTimeout(draw, 300);
    setTimeout(() => {
        window.location.href =  '../modules/welcome.php';
    }, 2000);
</script>
</body>
</html>